# Generated by Django 3.1.1 on 2020-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sub',
            field=models.CharField(max_length=300),
        ),
    ]
